services:
  wea_fe:
    image: hejsekvojtech/wea_fe
    container_name: wea_fe
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - cdb-network
  wea_db:
    image: mysql:9
    restart: unless-stopped
    container_name: wea_db
    ports:
      - "5006:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: WEAez
    networks:
      - cdb-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  sk07-web:
    image: hejsekvojtech/wea_be
    container_name: sk07-web
    depends_on:
      wea_db:
        condition: service_healthy
    build:
      context: ./modules/wea_be
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - /home/cerny/logs/sk07:/home/app/logs
    networks:
      - cdb-network
  sk07-proxy:
    image: nginx:latest
    container_name: sk07-proxy
    ports:
      - "3006:3006"
      - "8006:8006"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/server.conf
      - ./proxy/certs:/etc/certs
    networks:
      - cdb-network
    depends_on:
      - wea_fe
      - sk07-web
networks:
  cdb-network:
    name: cdb-network
    driver: bridge
    external: true