services:
  wea_fe:
    image: hejsekvojtech/wea_fe
    container_name: wea_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - wea_net
networks:
  wea_net:
    name: wea_net
    driver: bridge
